apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Ai-Todo-App.fullname" . }}-secret
  labels:
    {{- include "Ai-Todo-App.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.env.databaseUrl | quote }}
  better-auth-secret: {{ .Values.env.betterAuthSecret | quote }}
  openrouter-api-key: {{ .Values.env.openrouterApiKey | quote }}
  openai-domain-key: {{ .Values.env.openaiDomainKey | quote }}
